version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
      npm-major:
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
      actions-major:
        update-types:
          - major
